version: "3.4"
services:
  devcontainer:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        MUID: ${MUID}
        MGID: ${MGID}
        USERNAME: ${USERNAME}
    image: dev-mlir
    ipc: host
    cap_add:
      - SYS_PTRACE
    security_opt:
      - "seccomp=unconfined"
    volumes:
      - type: bind
        source: ${HOME}
        target: ${HOME}
